/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab9p2_juanflores__;
 
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author JD
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        txt_orderDate3 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txt_shipMode3 = new javax.swing.JTextField();
        txt_segment3 = new javax.swing.JTextField();
        txt_state3 = new javax.swing.JTextField();
        txt_productID3 = new javax.swing.JTextField();
        txt_ProductName3 = new javax.swing.JTextField();
        txt_sales3 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txt_orderID3 = new javax.swing.JTextField();
        txt_customerID3 = new javax.swing.JTextField();
        txt_postalCode3 = new javax.swing.JTextField();
        txt_country3 = new javax.swing.JTextField();
        txt_category3 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        txt_shipDate3 = new javax.swing.JTextField();
        txt_customerName3 = new javax.swing.JTextField();
        txt_city3 = new javax.swing.JTextField();
        txt_subCategory3 = new javax.swing.JTextField();
        txt_region3 = new javax.swing.JTextField();
        txt_quantity3 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        txt_Discount3 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        txt_profile3 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        btn_agregarRegistro3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        listOrders = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        listDetails = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        listCustomers = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        listProducts = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDatos = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista__ = new javax.swing.JTable();
        btn_subirtabla = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel61.setText("Order ID");

        jLabel62.setText("Segment");

        jLabel63.setText("Ship Mode");

        jLabel64.setText("State");

        jLabel65.setText("Product ID");

        jLabel66.setText("Product Name");

        jLabel67.setText("Sales");

        jLabel68.setText("Customer ID");

        jLabel69.setText("Country");

        jLabel70.setText("Order Date");

        jLabel71.setText("Category");

        jLabel72.setText("Postal Code");

        jLabel73.setText("Ship Date");

        jLabel74.setText("Customer Name");

        jLabel75.setText("City");

        jLabel76.setText("Region");

        jLabel77.setText("Sub-Category");

        jLabel78.setText("Quantity");

        jLabel79.setText("Discount");

        jLabel80.setText("Profile");

        btn_agregarRegistro3.setText("AGREGAR REGISTRO");
        btn_agregarRegistro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarRegistro3MouseClicked(evt);
            }
        });
        btn_agregarRegistro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarRegistro3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel67)
                    .addComponent(jLabel65)
                    .addComponent(jLabel63)
                    .addComponent(jLabel61)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel62)
                            .addComponent(jLabel64))
                        .addGap(12, 12, 12)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_shipMode3, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(txt_segment3)
                                .addComponent(txt_state3))
                            .addComponent(txt_productID3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addComponent(txt_postalCode3))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txt_orderID3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel68)
                                .addGap(18, 18, 18)
                                .addComponent(txt_customerID3))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel71)
                                .addGap(18, 18, 18)
                                .addComponent(txt_category3))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel69)
                                .addGap(18, 18, 18)
                                .addComponent(txt_country3))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addGap(18, 18, 18)
                                .addComponent(txt_orderDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel74)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_customerName3))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel75)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_city3))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel76)
                        .addGap(18, 18, 18)
                        .addComponent(txt_region3))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel77)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_subCategory3))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel73)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_shipDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel66)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ProductName3)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txt_sales3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel78)
                        .addGap(23, 23, 23)
                        .addComponent(txt_quantity3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel79)
                        .addGap(23, 23, 23)
                        .addComponent(txt_Discount3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel80)
                        .addGap(23, 23, 23)
                        .addComponent(txt_profile3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregarRegistro3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(309, 309, 309)
                    .addComponent(jLabel72)
                    .addContainerGap(512, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel61)
                            .addComponent(txt_orderDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel70)
                            .addComponent(jLabel73)
                            .addComponent(txt_shipDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_orderID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel63)
                            .addComponent(txt_shipMode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel68)
                            .addComponent(txt_customerID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel74)
                            .addComponent(txt_customerName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel62)
                            .addComponent(txt_segment3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel69)
                            .addComponent(txt_country3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel75)
                            .addComponent(txt_city3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel64)
                                    .addComponent(txt_state3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_postalCode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel76)
                                    .addComponent(txt_region3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel71)
                                    .addComponent(txt_category3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel77)
                                    .addComponent(txt_subCategory3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(txt_productID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(txt_ProductName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(txt_sales3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78)
                    .addComponent(txt_quantity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel79)
                    .addComponent(txt_Discount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel80)
                    .addComponent(txt_profile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btn_agregarRegistro3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(192, 192, 192)
                    .addComponent(jLabel72)
                    .addContainerGap(261, Short.MAX_VALUE)))
        );

        jTabbedPane4.addTab("Agregar Registro", jPanel9);

        listOrders.setBackground(new java.awt.Color(0, 102, 0));
        listOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listOrdersMouseClicked(evt);
            }
        });

        jLabel81.setForeground(new java.awt.Color(0, 0, 0));
        jLabel81.setText("ORDERS");

        javax.swing.GroupLayout listOrdersLayout = new javax.swing.GroupLayout(listOrders);
        listOrders.setLayout(listOrdersLayout);
        listOrdersLayout.setHorizontalGroup(
            listOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listOrdersLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel81)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        listOrdersLayout.setVerticalGroup(
            listOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listOrdersLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel81)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listDetails.setBackground(new java.awt.Color(255, 204, 0));
        listDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDetailsMouseClicked(evt);
            }
        });

        jLabel82.setForeground(new java.awt.Color(0, 0, 0));
        jLabel82.setText("DETAILS");

        javax.swing.GroupLayout listDetailsLayout = new javax.swing.GroupLayout(listDetails);
        listDetails.setLayout(listDetailsLayout);
        listDetailsLayout.setHorizontalGroup(
            listDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listDetailsLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel82)
                .addGap(57, 57, 57))
        );
        listDetailsLayout.setVerticalGroup(
            listDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listDetailsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel82)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listCustomers.setBackground(new java.awt.Color(255, 51, 51));
        listCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCustomersMouseClicked(evt);
            }
        });

        jLabel83.setForeground(new java.awt.Color(0, 0, 0));
        jLabel83.setText("CUSTOMERS");

        javax.swing.GroupLayout listCustomersLayout = new javax.swing.GroupLayout(listCustomers);
        listCustomers.setLayout(listCustomersLayout);
        listCustomersLayout.setHorizontalGroup(
            listCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listCustomersLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel83)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        listCustomersLayout.setVerticalGroup(
            listCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listCustomersLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel83)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        listProducts.setBackground(new java.awt.Color(102, 102, 255));
        listProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProductsMouseClicked(evt);
            }
        });

        jLabel84.setForeground(new java.awt.Color(0, 0, 0));
        jLabel84.setText("PRODUCTS");

        javax.swing.GroupLayout listProductsLayout = new javax.swing.GroupLayout(listProducts);
        listProducts.setLayout(listProductsLayout);
        listProductsLayout.setHorizontalGroup(
            listProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listProductsLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel84)
                .addGap(54, 54, 54))
        );
        listProductsLayout.setVerticalGroup(
            listProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listProductsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel84)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_limpiar.setText("CLEAR");
        btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limpiarMouseClicked(evt);
            }
        });

        textoDatos.setColumns(20);
        textoDatos.setRows(5);
        jScrollPane1.setViewportView(textoDatos);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(listOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(listDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(listCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(listProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Listar Registros", jPanel10);

        lista__.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Row ID", "Order ID", "OrderDate", "Customer ID", "Country", "City", "Product ID", "Sales"
            }
        ));
        jScrollPane2.setViewportView(lista__);

        btn_subirtabla.setText("Update Tabla");
        btn_subirtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_subirtablaMouseClicked(evt);
            }
        });

        btn_eliminar.setText("Eliminar Registro");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btn_subirtabla, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_subirtabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Eliminar Registros", jPanel11);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 796, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 527, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarRegistro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarRegistro3ActionPerformed
        
    }//GEN-LAST:event_btn_agregarRegistro3ActionPerformed

    private void listOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listOrdersMouseClicked
       
        Dba db = new Dba("./Lab9P2.accdb");
        db.conectar();
        try {
            db.query.execute("SELECT [Order ID], [Order Date], [Ship Date], [Ship Mode], [Customer ID]\n" +
"FROM TenRecord;");
            
            ResultSet rs = db.query.getResultSet();
          String texto = "";
            int o = 1;
            while(rs.next()){
              texto+= "Record "+o+"\n";
              texto+=  "Order ID : "+rs.getString(1)+"\n";
              texto+=  "Order Date: "+rs.getString(2)+"\n";
              texto+=  "Ship Date: "+rs.getString(3)+"\n";
              texto+=  "Ship Mode: "+rs.getString(4)+"\n";
              texto+=  "Customer ID: "+rs.getString(5)+"\n";
             
              texto+= "\n";
                                                                     
               o++;
            }
            textoDatos.setText(texto);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al listar");
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_listOrdersMouseClicked

    private void btn_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limpiarMouseClicked
        textoDatos.setText("");
    }//GEN-LAST:event_btn_limpiarMouseClicked

    private void listDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDetailsMouseClicked
      Dba db = new Dba("./Lab9P2.accdb");
        db.conectar();
        try {
            db.query.execute("SELECT [Order ID], [Product ID], [Sales], [Quantity], [Discount], [Profit]\n" +
"FROM TenRecord");
            
            ResultSet rs = db.query.getResultSet();
         String texto = "";
            int o = 1;
            while(rs.next()){
              texto+= "Record "+o+"\n";
              texto+=  "Order ID : "+rs.getString(1)+"\n";
              texto+=  "Product ID: "+rs.getString(2)+"\n";
              texto+=  "Sales: "+rs.getString(3)+"\n";
              texto+=  "Quantity: "+rs.getString(4)+"\n";
              texto+=  "Discount: "+rs.getString(5)+"\n";
              texto+=  "Profit: "+rs.getString(6)+"\n";
             
              texto+= "\n";
                                                                     
               o++;
            }
            textoDatos.setText(texto);
            
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(this, "Error al listar");
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_listDetailsMouseClicked

    private void listCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCustomersMouseClicked
        Dba db = new Dba("./Lab9P2.accdb");
        db.conectar();
        try {
            db.query.execute("SELECT [Customer ID], [Customer Name], [Segment], [Country], [City], [State],[Postal Code],[Region]\n" +
"FROM TenRecord");
            
            ResultSet rs = db.query.getResultSet();
           String texto = "";
            int o = 1;
            while(rs.next()){
              texto+= "Record "+o+"\n";
              texto+=  "Customer ID : "+rs.getString(1)+"\n";
              texto+=  "Customer Name: "+rs.getString(2)+"\n";
              texto+=  "Segment: "+rs.getString(3)+"\n";
              texto+=  "Country: "+rs.getString(4)+"\n";
              texto+=  "City: "+rs.getString(5)+"\n";
              texto+=  "State: "+rs.getString(6)+"\n";
              texto+=  "Postal Code: "+rs.getString(7)+"\n";
              texto+=  "Region: "+rs.getString(8)+"\n";
              texto+= "\n";
                                                                     
               o++;
            }
            textoDatos.setText(texto);
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(this, "Error al listar");
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_listCustomersMouseClicked

    private void listProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProductsMouseClicked
               Dba db = new Dba("./Lab9P2.accdb");
        db.conectar();
        try {
            db.query.execute("SELECT [Product ID], [Category], [Sub-Category], [Product Name]\n" +
"FROM TenRecord");
            
            ResultSet rs = db.query.getResultSet();
            String texto = "";
            int o = 1;
            while(rs.next()){
              texto+= "Record "+o+"\n";
              texto+=  "Product ID: "+rs.getString(1)+"\n";
              texto+=  "Category: "+rs.getString(2)+"\n";
              texto+=  "Sub-Category: "+rs.getString(3)+"\n";
              texto+=  "Product Name: "+rs.getString(4)+"\n";
              texto+= "\n";
                                                                     
               o++;
            }
            
            textoDatos.setText(texto);
            
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(this, "Error al listar");
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_listProductsMouseClicked

    private void btn_agregarRegistro3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarRegistro3MouseClicked
        Dba dbaa = new Dba("./Lab9P2.accdb");
        dbaa.conectar();
        
        
        try {
            String OrderID =txt_orderID3.getText();
             String OrderDate = txt_orderDate3.getText();
            String ShipDate = txt_shipDate3.getText();
            
            String ShipMode = txt_shipMode3.getText();
            String CustomerID = txt_customerID3.getText();
            String CustomerName = txt_customerName3.getText();
            
            String Segment = txt_segment3.getText();
            String Country = txt_country3.getText();
            String City = txt_city3.getText();         
            
            String State = txt_state3.getText();
            String PostalCode = txt_postalCode3.getText();
            String Region = txt_region3.getText();         
            
            String ProductID = txt_productID3.getText();
            String category = txt_category3.getText();
            String SubCategory = txt_subCategory3.getText();
            
            String productName = txt_ProductName3.getText();
            
            String Sales = txt_sales3.getText();
            String Quantity = txt_quantity3.getText();
            String Discount = txt_Discount3.getText();
            String Profile = txt_profile3.getText();
           
          dbaa.query.execute("INSERT INTO TenRecord"
                    + " ([Order ID], [Order Date], [Ship Date], [Ship Mode], [Customer ID], [Customer Name], [Segment], [Country], [City], [State], [Postal Code], [Region], [Product ID], [Category], [Sub-Category], [Product Name], [Sales], [Quantity], [Discount], [Profit])"
                    + " VALUES ('" + OrderID + "', '" + OrderDate +"', '"+ ShipDate +"', '"+ ShipMode+"', '"+ CustomerID+"', '"+ CustomerName+"', '"+ Segment +"', '"+ Country +"', '"+ City +"', '"+ State +"', '"+ PostalCode +"', '"+ Region +"', '"+ ProductID +"', '"+ category +"', '"+ SubCategory +"', '"+ productName+"', '"+ Sales +"', '"+ Quantity +"', '"+ Discount +"', '"+ Profile +"');");

            
            dbaa.commit();             
                                    

        } catch (SQLException e) {
             JOptionPane.showMessageDialog(this, "Error al agregar");
                e.printStackTrace();
        }
        
        dbaa.desconectar();
        
    txt_orderID3.setText("");
    txt_orderDate3.setText("");
    txt_shipDate3.setText("");

    txt_shipMode3.setText("");
    txt_customerID3.setText("");
    txt_customerName3.setText("");

    txt_segment3.setText("");
    txt_country3.setText("");
    txt_city3.setText("");         

    txt_state3.setText("");
    txt_postalCode3.setText("");
    txt_region3.setText("");       

    txt_productID3.setText("");
    txt_category3.setText("");
    txt_subCategory3.setText("");

    txt_ProductName3.setText("");

    txt_sales3.setText("");
    txt_quantity3.setText("");
    txt_Discount3.setText("");
    txt_profile3.setText("");
    
        JOptionPane.showMessageDialog(this, "registro agregado");
        
    }//GEN-LAST:event_btn_agregarRegistro3MouseClicked

    private void btn_subirtablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subirtablaMouseClicked
       
        
        Dba db = new Dba("./Lab9P2.accdb");
        
        db.conectar();
        
        try {
               db.query.execute("SELECT [RowID], [Order ID], [Order Date], [Customer ID],[Country],[City],[Product ID],[Sales]\n" +
               "FROM TenRecord");
            
            ResultSet rs = db.query.getResultSet();
           
            while(rs.next()){
             
             DefaultTableModel modelo = (DefaultTableModel) lista__.getModel();
              
             
              Object[] array = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
         
              modelo.addRow(array);
            
              lista__.setModel(modelo);
            }
            
                 
              
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(this, "Error al subir la tabla");
            e.printStackTrace();
        }
        
        db.desconectar();
    }//GEN-LAST:event_btn_subirtablaMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
      
       
        
        Dba dba = new Dba("./Lab9P2.accdb");
        
        dba.conectar(); 
        
        
        int id =lista__.getSelectedRow();
        
        try {
           DefaultTableModel modelo = (DefaultTableModel) lista__.getModel();
             dba.query.execute("delete from TenRecord where RowID = "+id+"");
            
           dba.commit();
           
         modelo.removeRow(id);
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el registro");
            e.printStackTrace();
        }
        
        
        dba.desconectar();
        
        

        
        
        
    }//GEN-LAST:event_btn_eliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarRegistro3;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_subirtabla;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JPanel listCustomers;
    private javax.swing.JPanel listDetails;
    private javax.swing.JPanel listOrders;
    private javax.swing.JPanel listProducts;
    private javax.swing.JTable lista__;
    private javax.swing.JTextArea textoDatos;
    private javax.swing.JTextField txt_Discount3;
    private javax.swing.JTextField txt_ProductName3;
    private javax.swing.JTextField txt_category3;
    private javax.swing.JTextField txt_city3;
    private javax.swing.JTextField txt_country3;
    private javax.swing.JTextField txt_customerID3;
    private javax.swing.JTextField txt_customerName3;
    private javax.swing.JTextField txt_orderDate3;
    private javax.swing.JTextField txt_orderID3;
    private javax.swing.JTextField txt_postalCode3;
    private javax.swing.JTextField txt_productID3;
    private javax.swing.JTextField txt_profile3;
    private javax.swing.JTextField txt_quantity3;
    private javax.swing.JTextField txt_region3;
    private javax.swing.JTextField txt_sales3;
    private javax.swing.JTextField txt_segment3;
    private javax.swing.JTextField txt_shipDate3;
    private javax.swing.JTextField txt_shipMode3;
    private javax.swing.JTextField txt_state3;
    private javax.swing.JTextField txt_subCategory3;
    // End of variables declaration//GEN-END:variables
}
